apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: newfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: media-service
          image: ghcr.io/tranloi2k/new-feed-microservices-media-service:a4aa6d3202a0d8dfa13720682ec95a542ee6d978
          ports:
            - containerPort: 3003
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: PORT
              value: "3003"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "384Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: newfeed
spec:
  selector:
    app: media-service
  ports:
    - port: 3003
      targetPort: 3003