apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-chat
  namespace: newfeed
spec:
  serviceName: postgres-chat
  replicas: 1
  selector:
    matchLabels:
      app: postgres-chat
  template:
    metadata:
      labels:
        app: postgres-chat
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: chat_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-chat
  namespace: newfeed
spec:
  selector:
    app: postgres-chat
  ports:
    - port: 5432
      targetPort: 5432
